# Generated by Django 5.2.7 on 2025-11-17 21:39

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patente', models.CharField(help_text='Patente del vehículo', max_length=10, unique=True)),
                ('tipo', models.CharField(choices=[('camioneta', 'Camioneta'), ('furgon', 'Furgón'), ('camion', 'Camión'), ('otro', 'Otro')], default='camioneta', max_length=20)),
                ('marca', models.CharField(max_length=50)),
                ('modelo', models.CharField(max_length=50)),
                ('año', models.PositiveIntegerField(help_text='Año del vehículo')),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('kilometraje_actual', models.PositiveIntegerField(default=0, help_text='Kilometraje actual en km')),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('en_mantenimiento', 'En Mantenimiento'), ('fuera_servicio', 'Fuera de Servicio')], default='disponible', max_length=20)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('proximo_mantenimiento_km', models.PositiveIntegerField(blank=True, help_text='Próximo mantenimiento en km', null=True)),
                ('seguro_vencimiento', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Vehículo',
                'verbose_name_plural': 'Vehículos',
                'ordering': ['patente'],
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('tipo_usuario', models.CharField(choices=[('administrador', 'Administrador'), ('repartidor', 'Repartidor'), ('cliente', 'Cliente')], default='cliente', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=12, unique=True)),
                ('tipo_cliente', models.CharField(choices=[('particular', 'Particular'), ('empresa', 'Empresa')], default='particular', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
            },
        ),
        migrations.CreateModel(
            name='Juego',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('categoria', models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=20)),
                ('edad_minima', models.PositiveIntegerField(default=3, help_text='Edad mínima en años')),
                ('edad_maxima', models.PositiveIntegerField(default=12, help_text='Edad máxima en años')),
                ('dimension_largo', models.FloatField(default=0.0, help_text='Largo en metros')),
                ('dimension_ancho', models.FloatField(default=0.0, help_text='Ancho en metros')),
                ('dimension_alto', models.FloatField(default=0.0, help_text='Alto en metros')),
                ('capacidad_personas', models.PositiveIntegerField()),
                ('peso_maximo', models.PositiveIntegerField(help_text='Peso máximo en kg')),
                ('precio_base', models.PositiveIntegerField()),
                ('foto', models.ImageField(blank=True, help_text='Imagen del juego inflable', null=True, upload_to='juegos/')),
                ('estado', models.CharField(choices=[('Habilitado', 'Habilitado'), ('Deshabilitado', 'Deshabilitado')], default='Habilitado', help_text='Estado actual del juego inflable', max_length=20)),
                ('peso_excedido', models.BooleanField(default=False, help_text='Indica si el peso excede el máximo de la categoría')),
                ('peso_excedido_fecha', models.DateTimeField(blank=True, help_text='Fecha y hora en que se ingresó el peso excedido', null=True)),
                ('peso_excedido_por', models.ForeignKey(blank=True, help_text='Usuario que ingresó el peso excedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juegos_peso_excedido', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Juego Inflable',
                'verbose_name_plural': 'Juegos Inflables',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(help_text='Código de cupón', max_length=50, unique=True)),
                ('nombre', models.CharField(help_text='Nombre de la promoción', max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('tipo_descuento', models.CharField(choices=[('porcentaje', 'Porcentaje (%)'), ('monto_fijo', 'Monto Fijo ($)'), ('2x1', '2x1'), ('envio_gratis', 'Envío Gratis')], default='porcentaje', max_length=20)),
                ('valor_descuento', models.DecimalField(decimal_places=2, help_text='Valor del descuento (porcentaje o monto según tipo)', max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('monto_minimo', models.DecimalField(decimal_places=2, default=0, help_text='Monto mínimo de compra para aplicar el descuento', max_digits=10)),
                ('limite_usos', models.PositiveIntegerField(default=0, help_text='Límite de usos (0 = ilimitado)')),
                ('usos_actuales', models.PositiveIntegerField(default=0, help_text='Usos actuales')),
                ('estado', models.CharField(choices=[('activa', 'Activa'), ('inactiva', 'Inactiva'), ('expirada', 'Expirada')], default='activa', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('juegos', models.ManyToManyField(blank=True, help_text='Juegos aplicables (vacío = todos)', related_name='promociones', to='jio_app.juego')),
            ],
            options={
                'verbose_name': 'Promoción',
                'verbose_name_plural': 'Promociones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Repartidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('licencia_conducir', models.CharField(blank=True, max_length=20, null=True)),
                ('vehiculo', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('Habilitado', 'Habilitado'), ('Deshabilitado', 'Deshabilitado')], default='Habilitado', max_length=20)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='repartidor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Repartidor',
                'verbose_name_plural': 'Repartidores',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_evento', models.DateField()),
                ('hora_instalacion', models.TimeField()),
                ('hora_retiro', models.TimeField()),
                ('direccion_evento', models.CharField(max_length=300)),
                ('estado', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('distancia_km', models.PositiveIntegerField(default=0, help_text='Kilómetros fuera de Osorno')),
                ('precio_distancia', models.DecimalField(decimal_places=2, default=0, help_text='Precio por distancia (km * precio por km)', max_digits=10)),
                ('horas_extra', models.PositiveIntegerField(default=0, help_text='Horas adicionales después de las 6 horas base')),
                ('precio_horas_extra', models.DecimalField(decimal_places=2, default=0, help_text='Precio por horas extra ($10.000 por hora)', max_digits=10)),
                ('total_reserva', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservas', to='jio_app.cliente')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('cheque', 'Cheque')], max_length=20)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagado', 'Pagado'), ('reembolsado', 'Reembolsado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('imagen_transferencia', models.CharField(blank=True, help_text='URL de la imagen de transferencia', max_length=200, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='jio_app.reserva')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Instalacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_instalacion', models.DateField()),
                ('hora_instalacion', models.TimeField()),
                ('direccion_instalacion', models.CharField(max_length=300)),
                ('telefono_cliente', models.CharField(max_length=15)),
                ('estado_instalacion', models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada'), ('pendiente', 'Pendiente'), ('cancelada', 'Cancelada')], default='programada', max_length=20)),
                ('observaciones_instalacion', models.TextField(blank=True, null=True)),
                ('metodo_pago', models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], max_length=20, null=True)),
                ('comprobante_pago', models.ImageField(blank=True, null=True, upload_to='comprobantes/')),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jio_app.repartidor')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='instalacion', to='jio_app.reserva')),
            ],
            options={
                'verbose_name': 'Instalación',
                'verbose_name_plural': 'Instalaciones',
            },
        ),
        migrations.CreateModel(
            name='Retiro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_retiro', models.DateField()),
                ('hora_retiro', models.TimeField()),
                ('estado_retiro', models.CharField(choices=[('programado', 'Programado'), ('realizado', 'Realizado'), ('pendiente', 'Pendiente'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('observaciones_retiro', models.TextField(blank=True, null=True)),
                ('repartidor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='jio_app.repartidor')),
                ('reserva', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='retiro', to='jio_app.reserva')),
            ],
            options={
                'verbose_name': 'Retiro',
                'verbose_name_plural': 'Retiros',
            },
        ),
        migrations.CreateModel(
            name='GastoOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(choices=[('combustible', 'Combustible'), ('mantenimiento', 'Mantenimiento'), ('publicidad', 'Publicidad'), ('servicios', 'Servicios'), ('materiales', 'Materiales'), ('salarios', 'Salarios'), ('alquiler', 'Alquiler'), ('seguros', 'Seguros'), ('impuestos', 'Impuestos'), ('otros', 'Otros')], max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_gasto', models.DateField()),
                ('metodo_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('tarjeta', 'Tarjeta'), ('cheque', 'Cheque')], max_length=20)),
                ('comprobante', models.ImageField(blank=True, null=True, upload_to='comprobantes_gastos/')),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('registrado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos_registrados', to=settings.AUTH_USER_MODEL)),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='jio_app.reserva')),
                ('vehiculo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gastos', to='jio_app.vehiculo')),
            ],
            options={
                'verbose_name': 'Gasto Operativo',
                'verbose_name_plural': 'Gastos Operativos',
                'ordering': ['-fecha_gasto', '-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PrecioTemporada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temporada', models.CharField(choices=[('Alta', 'Temporada Alta'), ('Baja', 'Temporada Baja'), ('Especial', 'Temporada Especial')], max_length=20)),
                ('precio_arriendo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('descuento_porcentaje', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precios_temporada', to='jio_app.juego')),
            ],
            options={
                'verbose_name': 'Precio por Temporada',
                'verbose_name_plural': 'Precios por Temporada',
                'unique_together': {('juego', 'temporada', 'fecha_inicio')},
            },
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.PositiveIntegerField(choices=[(1, '1 Estrella'), (2, '2 Estrellas'), (3, '3 Estrellas'), (4, '4 Estrellas'), (5, '5 Estrellas')])),
                ('comentario', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('publicada', 'Publicada'), ('pendiente', 'Pendiente'), ('oculta', 'Oculta')], default='pendiente', max_length=20)),
                ('respuesta_admin', models.TextField(blank=True, help_text='Respuesta del administrador', null=True)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='jio_app.cliente')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='jio_app.reserva')),
            ],
            options={
                'verbose_name': 'Evaluación',
                'verbose_name_plural': 'Evaluaciones',
                'ordering': ['-fecha_evaluacion'],
                'unique_together': {('reserva', 'cliente')},
            },
        ),
        migrations.CreateModel(
            name='DetalleReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('juego', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jio_app.juego')),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='jio_app.reserva')),
            ],
            options={
                'verbose_name': 'Detalle de Reserva',
                'verbose_name_plural': 'Detalles de Reserva',
                'unique_together': {('reserva', 'juego')},
            },
        ),
    ]
