# Generated by Django 5.2.7 on 2025-11-25 22:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preciotemporada',
            name='descuento_porcentaje',
            field=models.PositiveIntegerField(default=0, help_text='Descuento en porcentaje (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='preciotemporada',
            name='precio_arriendo',
            field=models.PositiveIntegerField(help_text='Precio de arriendo en pesos chilenos'),
        ),
    ]
