# Generated by Django 5.2.6 on 2025-11-03 05:37

from django.db import migrations, models
import re


def migrar_dimensiones(apps, schema_editor):
    """
    Migra datos del campo dimensiones (string) a los nuevos campos float
    """
    Juego = apps.get_model('jio_app', 'Juego')
    
    for juego in Juego.objects.all():
        if hasattr(juego, 'dimensiones') and juego.dimensiones:
            # Intentar parsear formato "5m x 3m x 2m" o "5 x 3 x 2"
            dimensiones_str = juego.dimensiones.replace('m', '').replace('M', '').strip()
            partes = re.split(r'\s*x\s*|X|\s+', dimensiones_str)
            
            if len(partes) >= 3:
                try:
                    juego.dimension_largo = float(partes[0].strip())
                    juego.dimension_ancho = float(partes[1].strip())
                    juego.dimension_alto = float(partes[2].strip())
                    juego.save()
                except (ValueError, IndexError):
                    # Si no se puede parsear, dejar valores por defecto (0.0)
                    pass


class Migration(migrations.Migration):

    dependencies = [
        ('jio_app', '0001_initial'),
    ]

    operations = [
        # Primero agregar los nuevos campos
        migrations.AddField(
            model_name='juego',
            name='dimension_alto',
            field=models.FloatField(default=0.0, help_text='Alto en metros'),
        ),
        migrations.AddField(
            model_name='juego',
            name='dimension_ancho',
            field=models.FloatField(default=0.0, help_text='Ancho en metros'),
        ),
        migrations.AddField(
            model_name='juego',
            name='dimension_largo',
            field=models.FloatField(default=0.0, help_text='Largo en metros'),
        ),
        # Migrar datos
        migrations.RunPython(migrar_dimensiones, migrations.RunPython.noop),
        # Finalmente eliminar el campo viejo
        migrations.RemoveField(
            model_name='juego',
            name='dimensiones',
        ),
    ]
