# Generated by Django 5.2.7 on 2025-11-17 22:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jio_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del proveedor', max_length=100)),
                ('tipo_proveedor', models.CharField(choices=[('mantenimiento', 'Mantenimiento Vehículos'), ('combustible', 'Combustible'), ('seguros', 'Seguros'), ('materiales', 'Materiales/Repuestos'), ('servicios', 'Servicios Generales'), ('otros', 'Otros')], max_length=20)),
                ('rut', models.CharField(blank=True, help_text='RUT del proveedor', max_length=12, null=True)),
                ('contacto_nombre', models.CharField(blank=True, help_text='Nombre de contacto', max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('direccion', models.CharField(blank=True, max_length=200, null=True)),
                ('servicios_ofrecidos', models.TextField(blank=True, help_text='Descripción de servicios ofrecidos', null=True)),
                ('activo', models.BooleanField(default=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del material/equipo', max_length=100)),
                ('categoria', models.CharField(choices=[('bomba', 'Bomba de Aire'), ('extension', 'Extensiones Eléctricas'), ('accesorio', 'Accesorios'), ('repuesto', 'Repuestos'), ('herramienta', 'Herramientas'), ('limpieza', 'Productos de Limpieza'), ('otro', 'Otro')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('stock_actual', models.PositiveIntegerField(default=0, help_text='Cantidad disponible')),
                ('stock_minimo', models.PositiveIntegerField(default=0, help_text='Stock mínimo antes de alertar')),
                ('unidad_medida', models.CharField(default='unidad', help_text='Ej: unidad, metro, litro, kg', max_length=20)),
                ('precio_unitario', models.DecimalField(decimal_places=2, default=0, help_text='Precio de compra unitario', max_digits=10)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('mantenimiento', 'En Mantenimiento'), ('dañado', 'Dañado'), ('baja', 'Dado de Baja')], default='disponible', max_length=20)),
                ('ubicacion', models.CharField(blank=True, help_text='Ubicación física del material', max_length=100, null=True)),
                ('fecha_ultima_compra', models.DateField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materiales', to='jio_app.proveedor')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='MantenimientoVehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_mantenimiento', models.CharField(choices=[('preventivo', 'Preventivo'), ('correctivo', 'Correctivo'), ('revision', 'Revisión'), ('reparacion', 'Reparación')], max_length=20)),
                ('fecha_programada', models.DateField()),
                ('fecha_realizada', models.DateField(blank=True, null=True)),
                ('kilometraje', models.PositiveIntegerField(help_text='Kilometraje al momento del mantenimiento')),
                ('descripcion', models.TextField(help_text='Descripción del trabajo realizado')),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('programado', 'Programado'), ('en_proceso', 'En Proceso'), ('completado', 'Completado'), ('cancelado', 'Cancelado')], default='programado', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_modificacion', models.DateTimeField(auto_now=True)),
                ('realizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos_realizados', to=settings.AUTH_USER_MODEL)),
                ('vehiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mantenimientos', to='jio_app.vehiculo')),
                ('proveedor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mantenimientos', to='jio_app.proveedor')),
            ],
            options={
                'verbose_name': 'Mantenimiento de Vehículo',
                'verbose_name_plural': 'Mantenimientos de Vehículos',
                'ordering': ['-fecha_programada', '-fecha_creacion'],
            },
        ),
    ]
