# Generated by Django 5.2.7 on 2025-12-03 01:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jio_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='monto_descuento',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Monto del descuento aplicado', max_digits=10),
        ),
        migrations.AddField(
            model_name='reserva',
            name='promocion',
            field=models.ForeignKey(blank=True, help_text='Promoción aplicada', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='jio_app.promocion'),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='total_reserva',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total después del descuento', max_digits=10),
        ),
        migrations.CreateModel(
            name='UsoPromocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Email del cliente que usó el código', max_length=254)),
                ('fecha_uso', models.DateTimeField(auto_now_add=True)),
                ('promocion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usos', to='jio_app.promocion')),
                ('reserva', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uso_promocion', to='jio_app.reserva')),
            ],
            options={
                'verbose_name': 'Uso de Promoción',
                'verbose_name_plural': 'Usos de Promociones',
                'ordering': ['-fecha_uso'],
                'unique_together': {('promocion', 'email')},
            },
        ),
    ]
