# Generated by Django 5.2.2 on 2025-10-29 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jio_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='precio_base',
            field=models.PositiveIntegerField(),
        ),
    ]
