# Generated by Django 5.2.6 on 2025-11-04 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jio_app', '0002_remove_juego_dimensiones_juego_dimension_alto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='estado',
            field=models.CharField(choices=[('Habilitado', 'Habilitado'), ('Deshabilitado', 'Deshabilitado')], default='Habilitado', help_text='Estado actual del juego inflable', max_length=20),
        ),
        migrations.AlterField(
            model_name='juego',
            name='foto',
            field=models.ImageField(blank=True, help_text='Imagen del juego inflable', null=True, upload_to='juegos/'),
        ),
    ]
