# Generated by Django 5.2.6 on 2025-11-03 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jio_app', '0002_remove_juego_dimensiones_juego_dimension_alto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='distancia_km',
            field=models.PositiveIntegerField(default=0, help_text='Kilómetros fuera de Osorno'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_distancia',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio por distancia (km * precio por km)', max_digits=10),
        ),
    ]
