# Generated by Django 5.2.6 on 2025-11-06 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jio_app', '0003_alter_juego_estado_alter_juego_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='horas_extra',
            field=models.PositiveIntegerField(default=0, help_text='Horas adicionales después de las 6 horas base'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='precio_horas_extra',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Precio por horas extra ($10.000 por hora)', max_digits=10),
        ),
    ]
