# Generated by Django 5.2.6 on 2025-10-30 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jio_app', '0002_instalacion_comprobante_pago_instalacion_metodo_pago'),
        ('jio_app', '0003_alter_juego_precio_base'),
    ]

    operations = [
    ]
