# Generated by Django 5.2.6 on 2025-10-30 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jio_app', '0004_merge_20251030_0012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instalacion',
            name='metodo_pago',
            field=models.CharField(blank=True, choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('otro', 'Otro')], max_length=20, null=True),
        ),
    ]
