# Generated by Django 5.2.6 on 2025-11-06 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jio_app', '0004_reserva_horas_extra_reserva_precio_horas_extra'),
    ]

    operations = [
        migrations.AddField(
            model_name='juego',
            name='edad_maxima',
            field=models.PositiveIntegerField(default=12, help_text='Edad máxima en años'),
        ),
        migrations.AddField(
            model_name='juego',
            name='edad_minima',
            field=models.PositiveIntegerField(default=3, help_text='Edad mínima en años'),
        ),
        migrations.AddField(
            model_name='juego',
            name='peso_excedido',
            field=models.BooleanField(default=False, help_text='Indica si el peso excede el máximo de la categoría'),
        ),
        migrations.AddField(
            model_name='juego',
            name='peso_excedido_fecha',
            field=models.DateTimeField(blank=True, help_text='Fecha y hora en que se ingresó el peso excedido', null=True),
        ),
        migrations.AddField(
            model_name='juego',
            name='peso_excedido_por',
            field=models.ForeignKey(blank=True, help_text='Usuario que ingresó el peso excedido', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='juegos_peso_excedido', to=settings.AUTH_USER_MODEL),
        ),
    ]
