# Generated by Django 5.2.6 on 2025-10-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jio_app', '0005_alter_instalacion_metodo_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='categoria',
            field=models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], max_length=20),
        ),
        migrations.AlterField(
            model_name='juego',
            name='foto',
            field=models.ImageField(blank=True, help_text='Imagen del juego inflable', null=True, upload_to='juegos/'),
        ),
    ]
