# Generated by Django 5.2.6 on 2025-10-30 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jio_app', '0006_alter_juego_categoria_alter_juego_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='estado',
            field=models.CharField(choices=[('habilitado', 'Habilitado'), ('deshabilitado', 'Deshabilitado')], default='habilitado', help_text='Estado actual del juego inflable', max_length=20),
        ),
    ]
