# Generated by Django 5.2.6 on 2025-10-30 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jio_app', '0007_alter_juego_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='juego',
            name='estado',
            field=models.CharField(choices=[('Habilitado', 'Habilitado'), ('Deshabilitado', 'Deshabilitado')], default='Habilitado', help_text='Estado actual del juego inflable', max_length=20),
        ),
        migrations.AlterField(
            model_name='preciotemporada',
            name='temporada',
            field=models.CharField(choices=[('Alta', 'Temporada Alta'), ('Baja', 'Temporada Baja'), ('Especial', 'Temporada Especial')], max_length=20),
        ),
        migrations.AlterField(
            model_name='repartidor',
            name='estado',
            field=models.CharField(choices=[('Habilitado', 'Habilitado'), ('Deshabilitado', 'Deshabilitado')], default='Habilitado', max_length=20),
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('Pendiente', 'Pendiente'), ('Confirmada', 'Confirmada'), ('cancelada', 'Cancelada'), ('completada', 'Completada')], default='pendiente', max_length=20),
        ),
    ]
